# NB no need to recreate a new one for IosevkaCustom
# or any other - they can go in here to the same config
# (Wish i'd saved the previous one!)

[buildPlans.IosevkaQuasiProportional]
family = "Iosevka Quasi Proportional"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

[buildPlans.IosevkaQuasiProportional.variants.design]
one = "no-base"
four = "open-serifless"
seven = "straight-serifless-crossbar"
capital-i = "short-serifed"
capital-j = "serifless"
capital-z = "straight-serifless-with-horizontal-crossbar"
a = "single-storey-serifless"
i = "hooky"
j = "flat-hook-serifless"
l = "flat-tailed"
t = "bent-hook"
z = "straight-serifless"

[buildPlans.IosevkaQuasiProportional.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaQuasiProportional.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IosevkaQuasiProportional.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.IosevkaQuasiProportional.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.IosevkaQuasiProportional.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaQuasiProportional.widths.Extended]
shape = 720
menu = 7
css = "expanded"

[buildPlans.IosevkaQuasiProportional.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaQuasiProportional.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"


# --------------------------------------------------------


[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

[buildPlans.IosevkaCustom.variants.design]
one = "no-base"
four = "open-serifless"
seven = "straight-serifless-crossbar"
zero = "slashed"
capital-g = "toothless-rounded-serifless-hooked"
capital-j = "serifless"
capital-q = "vertical-crossing"
capital-z = "straight-serifless-with-horizontal-crossbar"
a = "single-storey-serifless"
f = "serifless"
i = "hooky"
j = "serifless"
k = "curly-serifless"
l = "semi-tailed"
m = "serifless"
q = "diagonal-tailed-serifless"
t = "bent-hook"

[buildPlans.IosevkaCustom.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustom.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustom.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.IosevkaCustom.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.IosevkaCustom.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.IosevkaCustom.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaCustom.widths.Extended]
shape = 720
menu = 7
css = "expanded"

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustom.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

# --------------------------------------------------------

[buildPlans.IosevkaTerm]
family = "Iosevka Term"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

[buildPlans.IosevkaTerm.variants.design]
four = "open-serifless"
seven = "straight-serifless-crossbar"
capital-j = "serifless"

[buildPlans.IosevkaTerm.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaTerm.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.IosevkaTerm.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.IosevkaTerm.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.IosevkaTerm.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.IosevkaTerm.widths.Condensed]
shape = 456
menu = 3
css = "condensed"

[buildPlans.IosevkaTerm.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaTerm.widths.SemiCondensed]
shape = 548
menu = 4
css = "semi-condensed"

[buildPlans.IosevkaTerm.widths.SemiExtended]
shape = 658
menu = 6
css = "semi-expanded"

[buildPlans.IosevkaTerm.widths.Extended]
shape = 720
menu = 7
css = "expanded"

[buildPlans.IosevkaTerm.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaTerm.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
